App\CrmBundle\Entity\Customer:
    type: entity
    table: app_customer
    repositoryClass: App\CrmBundle\Repository\CustomerRepository
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        metAt:
            type: datetime
            nullable: true
        status:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
