Core\UserBundle\Entity\User:
    exclusion_policy: all
    properties:
        email:
            type: string
        firstName:
            type: string
        lastName:
            type: string
        phone:
            type: string
        nationality:
            type: string
        roleLabel:
            type: string
        locale:
            type: string
        gender:
            type: string
        enabled:
            type: boolean
        locked:
            type: boolean
        roles:
            type: array
        groups:
            type: array
        transactionSeenList:
            type: array
        rentalSeenList:
            type: array
        phoneValidated:
            type: boolean
        phoneCode:
            type: string